### ISSUE TITLE
Portal-controlled sampling cannot be used for services onboarded to ASP.NET Core SDK 2.0 or higher

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-Announcements#15]
Currently [latest stable ASP.NET Core SDK 2.0 ](https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/2.0.0) is incompatible with portal-controlled sampling. Turning on server-side sampling from the ``Features and Pricing`` page results in all telemetry dropped for services onboarded with this SDK. We are working on the hotfix to stable 2.0 (planned 2.0.1) version of ASP.NET Core SDK. ETA is 6/16/2017

**Comment by AlexBulankou** [comment]
Updated announcement: we are planning to release a release a new stable version of ASP.NET Core SDK with the issue addressed. ETA is 6/16/2017.

**Comment by dnduffy** [comment]
The fix for server side sampling and a related correlation bug for the AppInsights .NET Core SDK has been released on nuget.org as version [2.0.1](https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/2.0.1).
The release notes can be found [here](https://github.com/Microsoft/ApplicationInsights-aspnetcore/releases/tag/v2.0.1).

**Comment by jawn** [comment]
So the issue can be closed?
